import type { Metadata } from "next";
import Link from "next/link";
import Userpage from "../../../postpage/page1";

export const metadata: Metadata = {
  title: "User Page",
  description: "Generated by TOny Collins",
};


const Users = async () => {

     const UsersP: Promise<UsersAll[]> = Userpage()
     const Users = await UsersP;
     console.log(Users)

  return (
    <div className="flex relative justify-center text-center flex-col mt-24">
      <h1><span className="text-2xl">HELLO  WORLD</span> To Our Users Page</h1>
      <Link href='/' className="hover:text-blue-500">TO Home Page</Link>
      <h1>Click on the box to see their post</h1>
      <br />
      <div className="relative grid justify-center grid-cols-[repeat(auto-fit,minmax(100px,350px))] gap-y-3 gap-x-8 mt-1">
        {Users.map((user:any) => 
        <div key={user.id}>
          <Link href={`/users/${user.id}`}>
            <div className=" w-[370px] h-auto shadow-md text-xl px-1 py-1 ">
              <div className="flex pt-2">
                <p>{user.id}. </p>
                <p>&nbsp;{(user.username).slice(0,10)} {(user.name).slice(0,23)}</p>
              </div>
              <div className="flex">
                <p>Email:</p>
                <p>&nbsp;{user.email}</p>
              </div>
              <div className="flex">
                <p>Phone No:</p>
                <p className="text-blue-700 cursor-pointer">&nbsp;
                {user.phone}
                </p>
              </div>
            </div>
          </Link>
        </div>)}
      </div>

    </div>
  )
}

export default Users


// {
//     "id": 1,
//     "name": "Leanne Graham",
//     "username": "Bret",
//     "email": "Sincere@april.biz",
//     "address": {
//       "street": "Kulas Light",
//       "suite": "Apt. 556",
//       "city": "Gwenborough",
//       "zipcode": "92998-3874",
//       "geo": {
//         "lat": "-37.3159",
//         "lng": "81.1496"
//       }
//     },
//     "phone": "1-770-736-8031 x56442",
//     "website": "hildegard.org",
//     "company": {
//       "name": "Romaguera-Crona",
//       "catchPhrase": "Multi-layered client-server neural-net",
//       "bs": "harness real-time e-markets"
//     }
//   }

//Posts
//  {
//     "userId": 1,
//     "it": 1,
//     "title": "are or do repels provide blacked out except option criticizes",
//     "body": "because he also accepts\nundertakes the consequences of refusal and when\nhe criticizes the trouble so that the whole\nof our things are but they are the matter will happen to the architect"
//   },